/**
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 * @attention
 
*/
#include <stdint.h>
#include "stm32f7xx_hal.h"
#include "gpio_driver.h"
#include "drain_loop.h"
#include "uart_frame.h"
#include "cli.h"
#include "spi_test.h"

/* WITHOUT THIS THE BOARD HANGS ~1 ms AFTER BOOT.
 *
 * HAL_Init() starts SysTick with its interrupt enabled. If SysTick_Handler is
 * not defined here, the linker aliases it to Default_Handler in
 * startup_stm32f767xx.S, which is:
 *
 *      Default_Handler:
 *      Infinite_Loop:
 *        b Infinite_Loop
 *
 * so the very first tick traps the CPU forever. Nothing in main() below ever
 * runs. It also means HAL_IncTick() is never called, so HAL_GetTick() returns
 * 0 permanently and every HAL timeout becomes an unbounded wait. */
void SysTick_Handler(void)
{
	HAL_IncTick();
}

static void SystemClock_Config(void)
{
	RCC_OscInitTypeDef osc = {0};
	RCC_ClkInitTypeDef clk = {0};

	__HAL_RCC_PWR_CLK_ENABLE(); //Turn on the clock for the PWR (power control) peripheral.
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1); //Configure the power regulator to voltage scale 1.

	/* Nucleo-144: X3 crystal not populated, HSE comes from the ST-LINK's
	 * MCO output, so this is an external clock (BYPASS), not a resonator. */
	osc.OscillatorType      = RCC_OSCILLATORTYPE_HSE; //For the oscillator, I want to use High Speed External
	osc.HSEState             = RCC_HSE_BYPASS;// The HSE is bypassed, meaning we are using an external clock source rather than a crystal oscillator.
	osc.PLL.PLLState         = RCC_PLL_ON;// The PLL is enabled.
	osc.PLL.PLLSource        = RCC_PLLSOURCE_HSE;// The PLL source is set to the HSE (High-Speed External) oscillator.
	osc.PLL.PLLM             = 8;    //Divide the HSE clock by 8 before feeding it into the PLL
	osc.PLL.PLLN             = 432;   //This means the PLL multiplication factor is 432.
	osc.PLL.PLLP             = RCC_PLLP_DIV2;  //Take the 432 MHz PLL output and divide it by 2 for the main system clock.
	osc.PLL.PLLQ             = 9;     /* 432 / 9     = 48 MHz for USB/SDMMC  */
	if (HAL_RCC_OscConfig(&osc) != HAL_OK) // Configure the oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
	{
		while (1);
	}

	/* Moved to AFTER OscConfig to match ST's reference sequence. Above
	 * 180 MHz the internal regulator has to be in overdrive before the
	 * clock switch happens. */
	if (HAL_PWREx_EnableOverDrive() != HAL_OK)
	{
		while (1);
	}

	clk.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
	                    | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
	clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
	clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;   /* HCLK  = 216 MHz              */
	clk.APB1CLKDivider = RCC_HCLK_DIV4;     /* PCLK1 =  54 MHz (max 54)     */
	clk.APB2CLKDivider = RCC_HCLK_DIV2;     /* PCLK2 = 108 MHz (max 108)    */
	/* FLASH_LATENCY_7: flash is far slower than 216 MHz and needs 7 wait
	 * states. This call also updates SystemCoreClock, which delay_us()
	 * depends on - which is why drain_loop_init() comes after it. */
	if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_7) != HAL_OK)
	{
		while (1);
	}
}

int main(void)
{
	HAL_Init();
	SystemClock_Config();
	gpio_init();
	drain_loop_init();
	uart_frame_init();
	spi_test_init();

	cli_init();
	cli_run();     /* never returns */
}